# Generated by Django 4.2.9 on 2026-03-24 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('compra_producto', 'Compra de Producto'), ('sueldos', 'Sueldos'), ('alquiler', 'Alquiler'), ('servicios', 'Servicios (Luz/Agua/Internet)'), ('mantenimiento', 'Mantenimiento'), ('otros', 'Otros')], default='otros', max_length=30)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('comprobante', models.CharField(blank=True, max_length=100, verbose_name='N° Comprobante')),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Egreso',
                'verbose_name_plural': 'Egresos',
                'ordering': ['-fecha'],
            },
        ),
    ]
