# Generated by Django 4.2.9 on 2026-04-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egreso',
            name='comprobante',
        ),
        migrations.RemoveField(
            model_name='egreso',
            name='notas',
        ),
        migrations.AlterField(
            model_name='egreso',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
