# Generated by Django 4.2.9 on 2026-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('snack', 'Snack'), ('suplemento', 'Suplemento')], default='snack', max_length=20),
        ),
    ]
