# Generated by Django 4.2.9 on 2026-03-24 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('membresia_por_vencer', 'Membresía por Vencer'), ('membresia_vencida', 'Membresía Vencida'), ('stock_bajo', 'Stock Bajo'), ('caja_abierta', 'Caja Abierta'), ('otro', 'Otro')], max_length=30)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('leida', 'Leída'), ('resuelta', 'Resuelta')], default='activa', max_length=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia_modelo', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha'],
            },
        ),
    ]
