# Generated by Django 4.2.9 on 2026-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.AddField(
            model_name='cliente',
            name='peso_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso Inicial (Kg)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ubicación'),
        ),
    ]
