# Generated by Django 4.2.9 on 2026-03-24 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_dias', models.PositiveIntegerField(verbose_name='Duración (días)')),
                ('estado', models.BooleanField(default=True, verbose_name='Activa')),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClienteMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='clientes.cliente')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membresias.membresia')),
            ],
            options={
                'verbose_name': 'Membresía de Cliente',
                'verbose_name_plural': 'Membresías de Clientes',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
