# Generated by Django 4.2.9 on 2026-03-24 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemembresia',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
    ]
