# Generated by Django 4.2.9 on 2026-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemembresia',
            name='peso_registro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (Kg)'),
        ),
    ]
