# Generated by Django 4.2.9 on 2026-05-11 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0004_clientemembresia_usuario_membresia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemembresia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
