# Generated by Django 4.2.9 on 2026-10-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='disciplina',
            field=models.CharField(blank=True, choices=[('gimnasio', 'Gimnasio'), ('crossfit', 'Crossfit'), ('kickboxing', 'Kick Boxing')], default='gimnasio', max_length=20, verbose_name='Disciplina'),
        ),
    ]
