# Generated by Django 4.2.9 on 2026-03-24 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='ClienteOcasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Visitante', max_length=150)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(default='efectivo', max_length=20)),
            ],
            options={
                'verbose_name': 'Cliente Ocasional',
                'verbose_name_plural': 'Clientes Ocasionales',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
