# Generated by Django 4.2.9 on 2026-10-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_usuario'),
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='disciplina',
            field=models.CharField(choices=[('gimnasio', 'Gimnasio'), ('crossfit', 'Crossfit'), ('kickboxing', 'Kick Boxing')], default='gimnasio', max_length=20, verbose_name='Disciplina / Área'),
        ),
        migrations.AddField(
            model_name='clienteocasional',
            name='disciplina',
            field=models.CharField(choices=[('gimnasio', 'Gimnasio'), ('crossfit', 'Crossfit'), ('kickboxing', 'Kick Boxing')], default='gimnasio', max_length=20, verbose_name='Disciplina / Área'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('cliente', 'fecha', 'disciplina')},
        ),
    ]
